"""Repository and Unit of Work protocols.

Repositories speak domain models only. ORM entities must never cross this boundary,
and no route handler or Agent runtime may bypass it.
"""

from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Protocol, Self, runtime_checkable

from agtyle.domain.actions import ActionRequest, ActionResult, PolicyDecision
from agtyle.domain.agents import AgentRun
from agtyle.domain.approvals import Approval
from agtyle.domain.artifacts import Artifact
from agtyle.domain.events import Event
from agtyle.domain.intents import Intent
from agtyle.domain.notifications import Notification
from agtyle.domain.registry_snapshot import AgentSnapshot, CapabilitySnapshot
from agtyle.domain.reminders import Reminder
from agtyle.domain.tasks import Task


class ConcurrentUpdateError(RuntimeError):
    """Raised when an optimistic update matched no row, meaning another process won."""


@runtime_checkable
class IntentRepository(Protocol):
    async def add(self, intent: Intent) -> None: ...
    async def get(self, intent_id: str) -> Intent | None: ...
    async def find_by_idempotency_key(self, *, user_id: str, key: str) -> Intent | None: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class TaskRepository(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get(self, task_id: str) -> Task | None: ...
    async def list_by_intent(self, intent_id: str) -> list[Task]: ...
    async def update(self, task: Task, *, expected_row_version: int) -> None:
        """Optimistic update. Raises ``ConcurrentUpdateError`` when the version moved on."""
        ...

    async def claim_next_assigned(
        self, *, owner: str, now: datetime, lease_seconds: int
    ) -> Task | None:
        """Conditionally claim the oldest claimable assigned Task, or return ``None``."""
        ...

    async def list_expired_running(self, *, now: datetime, limit: int = 100) -> list[Task]: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class AgentRunRepository(Protocol):
    async def add(self, run: AgentRun) -> None: ...
    async def get(self, run_id: str) -> AgentRun | None: ...
    async def update(self, run: AgentRun) -> None: ...
    async def list_for_task(self, task_id: str) -> list[AgentRun]: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class ActionRepository(Protocol):
    async def add(self, request: ActionRequest) -> None: ...
    async def get(self, action_request_id: str) -> ActionRequest | None: ...
    async def get_by_idempotency_key(self, key: str) -> ActionRequest | None: ...
    async def update(self, request: ActionRequest, *, expected_row_version: int) -> None: ...
    async def list_for_task(self, task_id: str) -> list[ActionRequest]: ...

    async def add_policy_decision(self, decision: PolicyDecision) -> None: ...
    async def list_policy_decisions(self, action_request_id: str) -> list[PolicyDecision]: ...

    async def add_result(self, result: ActionResult) -> None: ...
    async def get_result(self, action_request_id: str) -> ActionResult | None: ...

    async def add_artifact(self, artifact: Artifact) -> None: ...
    async def list_artifacts(self, task_id: str) -> list[Artifact]: ...

    async def count_requests(self) -> int: ...
    async def count_decisions(self) -> int: ...
    async def count_results(self) -> int: ...


@runtime_checkable
class ApprovalRepository(Protocol):
    async def add(self, approval: Approval) -> None: ...
    async def get(self, approval_id: str) -> Approval | None: ...
    async def update(self, approval: Approval, *, expected_row_version: int) -> None: ...
    async def list_for_action(self, action_request_id: str) -> list[Approval]: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class ReminderRepository(Protocol):
    async def add(self, reminder: Reminder) -> None: ...
    async def get(self, reminder_id: str) -> Reminder | None: ...
    async def get_by_idempotency_key(self, *, user_id: str, key: str) -> Reminder | None: ...
    async def update(self, reminder: Reminder, *, expected_row_version: int) -> None: ...
    async def claim_next_due(
        self, *, owner: str, now: datetime, lease_seconds: int
    ) -> Reminder | None: ...
    async def list_for_task(self, task_id: str) -> list[Reminder]: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class NotificationRepository(Protocol):
    async def add(self, notification: Notification) -> None: ...
    async def get(self, notification_id: str) -> Notification | None: ...
    async def get_by_delivery_key(self, delivery_key: str) -> Notification | None: ...
    async def update(self, notification: Notification, *, expected_row_version: int) -> None: ...
    async def claim_next_pending(
        self, *, owner: str, now: datetime, lease_seconds: int
    ) -> Notification | None: ...
    async def list_for_task(self, task_id: str) -> list[Notification]: ...
    async def list_for_reminder(self, reminder_id: str) -> list[Notification]: ...
    async def list_expired_delivering(
        self, *, now: datetime, limit: int = 100
    ) -> list[Notification]: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class RegistryRepository(Protocol):
    """Durable snapshots of the Agent and Capability registry, for audit and startup comparison."""

    async def list_agents(self) -> list[AgentSnapshot]: ...
    async def list_capabilities(self) -> list[CapabilitySnapshot]: ...
    async def upsert_agent(self, snapshot: AgentSnapshot) -> None: ...
    async def upsert_capability(self, snapshot: CapabilitySnapshot) -> None: ...
    async def disable_missing_agents(self, keep: list[tuple[str, int]]) -> int: ...
    async def disable_missing_capabilities(self, keep: list[tuple[str, int]]) -> int: ...


@runtime_checkable
class EventRepository(Protocol):
    """Append and query only. Mutation is rejected here and by database triggers."""

    async def append(self, event: Event) -> None: ...
    async def list_by_subject(self, subject: str) -> list[Event]: ...
    async def list_by_subjects(self, subjects: list[str]) -> list[Event]: ...
    async def count_all(self) -> int: ...


@runtime_checkable
class UnitOfWorkPort(Protocol):
    """One transaction across every repository. Nothing is visible before ``commit``."""

    intents: IntentRepository
    tasks: TaskRepository
    agent_runs: AgentRunRepository
    actions: ActionRepository
    approvals: ApprovalRepository
    reminders: ReminderRepository
    notifications: NotificationRepository
    events: EventRepository
    registry: RegistryRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


@runtime_checkable
class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWorkPort: ...
